name: Pull Request Validation
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled]

jobs:
    check-pr-metadata:
    name: Check PR title and reviewers
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title Format
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const pattern = /^[A-Z]+-\d+/; // e.g., "ABC-123: Add login"
            if (!pattern.test(title)) {
              core.setFailed(`❌ PR title "${title}" does not match required format (e.g., ABC-123: Add login)`);
            }


    lint-and-test:
    name: Run Linter and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run flake8 (Lint Check)
        run: |
          flake8 .
      
      - name: Run Tests
        run: |
          pytest